package com.pushengage.pushengage.Database

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Exercises [DaoInterface] insert/query/delete operations against an in-memory Room database.
 * The production database uses an on-disk store; the schema and DAO contract are identical, so
 * Robolectric + Room's in-memory builder gives us a fast, hermetic verification.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [28])
class DaoInterfaceTest {

    private lateinit var db: PERoomDatabase
    private lateinit var dao: DaoInterface

    @Before
    fun setUp() {
        val context: Context = ApplicationProvider.getApplicationContext()
        db = Room.inMemoryDatabaseBuilder(context, PERoomDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        dao = db.daoInterface()
    }

    @After
    fun tearDown() {
        db.close()
    }

    // ---- Channel CRUD ----

    @Test
    fun insertChannel_thenGetChannel_returnsSameEntity() {
        val channel = newChannel("chan_1", "name_1")
        dao.insert(channel)

        val fetched = dao.getChannel("chan_1")
        assertNotNull(fetched)
        assertEquals("chan_1", fetched!!.channelId)
        assertEquals("name_1", fetched.channelName)
        assertEquals("desc", fetched.channelDescription)
        assertEquals("group_id", fetched.groupId)
        assertEquals(true, fetched.badges)
    }

    @Test
    fun getChannel_missingId_returnsNull() {
        assertNull(dao.getChannel("does_not_exist"))
    }

    @Test
    fun insertChannel_sameId_replacesPrevious() {
        dao.insert(newChannel("chan_1", "first"))
        dao.insert(newChannel("chan_1", "second"))

        val fetched = dao.getChannel("chan_1")
        assertNotNull(fetched)
        assertEquals("second", fetched!!.channelName)
    }

    @Test
    fun deleteChannels_removesAll() {
        dao.insert(newChannel("chan_1", "a"))
        dao.insert(newChannel("chan_2", "b"))

        dao.deleteChannels()

        assertNull(dao.getChannel("chan_1"))
        assertNull(dao.getChannel("chan_2"))
    }

    @Test
    fun deleteChannels_emptyTable_doesNotCrash() {
        dao.deleteChannels()
        assertNull(dao.getChannel("anything"))
    }

    // ---- ClickRequest CRUD ----

    @Test
    fun insertClickRequest_isReturnedByGetAllClick() {
        val click = ClickRequestEntity("hash_a", "tag_a", "action_a", "mobile", "android", "1.0", "UTC")
        dao.insertClickRequest(click)

        val all = dao.getAllClick()
        assertEquals(1, all.size)
        assertEquals("hash_a", all[0].deviceHash)
        assertEquals("tag_a", all[0].tag)
        assertEquals("action_a", all[0].action)
    }

    @Test
    fun getAllClick_emptyTable_returnsEmptyList() {
        assertTrue(dao.getAllClick().isEmpty())
    }

    @Test
    fun insertClickRequest_autoGeneratesUniqueIds() {
        dao.insertClickRequest(ClickRequestEntity("h1", "t1", "a1", "mobile", "android", "1.0", "UTC"))
        dao.insertClickRequest(ClickRequestEntity("h2", "t2", "a2", "mobile", "android", "1.0", "UTC"))
        dao.insertClickRequest(ClickRequestEntity("h3", "t3", "a3", "mobile", "android", "1.0", "UTC"))

        val all = dao.getAllClick()
        assertEquals(3, all.size)
        val ids = all.map { it.id }.toSet()
        assertEquals("autogenerated ids should be unique", 3, ids.size)
    }

    @Test
    fun deleteClick_byDeviceHashAndTag_removesMatchingRow() {
        dao.insertClickRequest(ClickRequestEntity("h1", "t1", "a1", "mobile", "android", "1.0", "UTC"))
        dao.insertClickRequest(ClickRequestEntity("h1", "t2", "a1", "mobile", "android", "1.0", "UTC"))
        dao.insertClickRequest(ClickRequestEntity("h2", "t1", "a1", "mobile", "android", "1.0", "UTC"))

        dao.deleteClick("h1", "t1")

        val remaining = dao.getAllClick()
        assertEquals(2, remaining.size)
        assertTrue(remaining.none { it.deviceHash == "h1" && it.tag == "t1" })
        assertTrue(remaining.any { it.deviceHash == "h1" && it.tag == "t2" })
        assertTrue(remaining.any { it.deviceHash == "h2" && it.tag == "t1" })
    }

    @Test
    fun deleteClick_nonMatchingPair_leavesTableIntact() {
        dao.insertClickRequest(ClickRequestEntity("h1", "t1", "a1", "mobile", "android", "1.0", "UTC"))
        dao.deleteClick("nope", "nope")

        assertEquals(1, dao.getAllClick().size)
    }

    @Test
    fun clickAndChannelTables_areIndependent() {
        dao.insert(newChannel("chan_1", "name"))
        dao.insertClickRequest(ClickRequestEntity("h1", "t1", "a1", "mobile", "android", "1.0", "UTC"))

        dao.deleteChannels()

        // Channels gone, clicks untouched.
        assertNull(dao.getChannel("chan_1"))
        assertEquals(1, dao.getAllClick().size)
    }

    // ---- PERoomDatabase singleton ----

    @Test
    fun getDatabase_returnsSameInstanceAcrossCalls() {
        val context: Context = ApplicationProvider.getApplicationContext()
        val first = PERoomDatabase.getDatabase(context)
        val second = PERoomDatabase.getDatabase(context)
        assertSame("getDatabase must return the cached singleton", first, second)
    }

    // ---- helpers ----

    private fun newChannel(id: String, name: String): ChannelEntity = ChannelEntity(
        id,
        name,
        "desc",
        "group_id",
        "group_name",
        "high",
        "default",
        "sound_file",
        "true",
        "0,500",
        "blue",
        "#0000FF",
        "#FF0000",
        true,
        "public"
    )
}
