package com.pushengage.pushengage.iam.action

/**
 * Interface for handling custom actions from in-app messages.
 * Implement this interface to handle custom actions defined in the message payload.
 */
interface IAMCustomActionHandler {
    /**
     * Called when a custom action is triggered from an in-app message.
     *
     * Route on `parameters["action"]` — the "Action name" entered for the
     * button on the PushEngage dashboard.
     *
     * @param actionId   The button's internal key within the message (e.g.
     *                   "t04B05"), generated by the dashboard. Not user-defined;
     *                   do not route on it.
     * @param parameters The button's parameters. `"action"` holds the dashboard
     *                   Action name; any other entries are passed through.
     */
    fun onCustomAction(actionId: String, parameters: Map<String, Any>)
} 